### PR TITLE
Add check for duplicated asset ids in order legs

### PR DESCRIPTION
**Pull request by haoze-grvt**

### CODE REVIEW

**Review by minhbsq — APPROVED** [review]
LGTM. But I'm thinking whether it's worth adding a fast path to cater for the majority of the cases where there's only 1 leg.

Multiple-legs are only for RFQ, and for RFQ the volume is super-tiny (not to mentioned that this will be only supported maybe 2-3 Quarters from Day 1). By enforcing this check we are actually penalising the majority case with memory allocation and double for loop

**Comment by haoze-grvt** [comment]
> LGTM. But I'm thinking whether it's worth adding a fast path to cater for the majority of the cases where there's only 1 leg.
> 
> Multiple-legs are only for RFQ, and for RFQ the volume is super-tiny (not to mentioned that this will be only supported maybe 2-3 Quarters from Day 1). By enforcing this check we are actually penalising the majority case with memory allocation and double for loop

this makes sense. I have updated to only check when there is more than 1 leg in order.

**Review by minhbsq — APPROVED** [review]
LGTM

**Comment by minhbsq** [comment]
Not urgent, but I marked this PR as lacking tests and we can add them at a later date. (there are a few already under the label `lacking-tests`)

**Comment by haoze-grvt** [comment]
> Not urgent, but I marked this PR as lacking tests and we can add them at a later date.

indeed, there is an rtf test for duplicated asset id, but the trade is not synced to contract fixture because there is no match in risk. We can add a forge test for this later.

**Pull request merged**
